INSERT INTO systems (id,name,short_name,country_code,country_name,region,authority,system_type,status,status_label,status_detail,signal_basis,confidence,timezone,official_url,last_checked_at,last_changed_at,freshness_minutes)
VALUES ('pa-panama-canal','Panama Canal','Panama Canal','PA','Panama','Americas','Panama Canal Authority','canal','degraded','Transit capacity restricted','Temporary transit-capacity restrictions are in force because of reduced precipitation; Panamax capacity tightens further on 15 September.','official_operations','official','America/Panama','https://pancanal.com/en/maritime-services/advisory-to-shipping/','2026-09-10T04:23:00Z','2026-08-21T00:00:00Z',1440)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sources (id,system_id,name,url,adapter,source_tier,poll_interval_minutes,parser_version,monitoring_mode)
VALUES ('pa-canal-advisories','pa-panama-canal','Panama Canal advisories to shipping','https://pancanal.com/en/maritime-services/advisory-to-shipping/','panama_canal',1,60,'1','operations')
ON CONFLICT (id) DO UPDATE SET parser_version=EXCLUDED.parser_version, monitoring_mode=EXCLUDED.monitoring_mode, poll_interval_minutes=EXCLUDED.poll_interval_minutes;

INSERT INTO events (id,system_id,country_code,country_name,region,event_type,status,severity,confidence,title,summary,operational_impact,workaround,starts_at,ends_at,resolved_at,all_day,source_name,source_url,source_tier,last_verified_at,recurrence,fingerprint)
VALUES ('pa-canal-capacity-20260903','pa-panama-canal','PA','Panama','Americas','canal_constraint','active','moderate','official','Panama Canal transit capacity reduced','Panama Canal Authority reduced available daily capacity to nine Neopanamax slots and twenty-five Panamax slots under temporary water-conservation measures.','Vessels without secured reservations may face longer waits; auction and booking competition may increase.','Use the Canal booking and reservation options where possible; the Authority states that a confirmed reservation is the only mechanism that guarantees a transit date.','2026-09-03T00:00:00-05:00','2026-09-15T00:00:00-05:00',NULL,TRUE,'Panama Canal Authority — Advisory A-29-2026','https://pancanal.com/en/panama-canal-adopts-additional-measures-to-address-reduced-precipitation-in-the-canal-watershed/',1,'2026-09-10T04:23:00Z',NULL,'pa-canal-capacity-20260903')
ON CONFLICT (id) DO NOTHING;

INSERT INTO events (id,system_id,country_code,country_name,region,event_type,status,severity,confidence,title,summary,operational_impact,workaround,starts_at,ends_at,resolved_at,all_day,source_name,source_url,source_tier,last_verified_at,recurrence,fingerprint)
VALUES ('pa-canal-capacity-20260915','pa-panama-canal','PA','Panama','Americas','canal_constraint','upcoming','moderate','official','Panama Canal Panamax capacity tightens further','From 15 September, available daily Panamax Locks slots decrease to twenty-three while the nine-slot Neopanamax limit continues.','The additional capacity reduction may increase waiting times for vessels without reservations and tighten booking availability.','Secure bookings in advance and monitor Panama Canal advisories for further changes.','2026-09-15T00:00:00-05:00',NULL,NULL,TRUE,'Panama Canal Authority — Advisory A-29-2026','https://pancanal.com/en/panama-canal-adopts-additional-measures-to-address-reduced-precipitation-in-the-canal-watershed/',1,'2026-09-10T04:23:00Z',NULL,'pa-canal-capacity-20260915')
ON CONFLICT (id) DO NOTHING;
