INSERT INTO systems (id,name,short_name,country_code,country_name,region,authority,system_type,status,status_label,status_detail,signal_basis,confidence,timezone,official_url,last_checked_at,last_changed_at,freshness_minutes) VALUES
('tr-turkish-straits','Turkish Straits','Turkish Straits','TR','Türkiye','Europe','Directorate General of Coastal Safety','strait','clear','Traffic windows published','The official Turkish Straits traffic service publishes open and suspended transit windows for the Istanbul and Çanakkale straits.','official_operations','official','Europe/Istanbul','https://www.kiyiemniyeti.gov.tr/strait_traffic','2026-09-10T05:30:00Z','2026-09-10T05:30:00Z',45),
('eg-suez-canal','Suez Canal','Suez Canal','EG','Egypt','Middle East & Africa','Suez Canal Authority','canal','clear','Navigation operating','Recent official Suez Canal Authority navigation updates show canal traffic continuing; this is bulletin monitoring rather than a continuous operational heartbeat.','official_operations','official','Africa/Cairo','https://www.suezcanal.gov.eg/English/pages/default.aspx?lang=en','2026-09-10T05:30:00Z','2026-08-22T00:00:00Z',43200),
('us-commercial-borders','U.S. Commercial Border Wait Times','U.S. Border Waits','US','United States','Americas','U.S. Customs and Border Protection','border','unknown','Awaiting live check','CBP publishes current commercial-vehicle wait times and lane availability for land ports of entry on the Canadian and Mexican borders.','official_operations','official','America/New_York','https://bwt.cbp.gov/ViewAllPorts',NULL,NULL,45)
ON CONFLICT (id) DO NOTHING;

INSERT INTO sources (id,system_id,name,url,adapter,source_tier,poll_interval_minutes,parser_version,monitoring_mode) VALUES
('tr-straits-traffic','tr-turkish-straits','Turkish Straits traffic direction','https://www.kiyiemniyeti.gov.tr/strait_traffic','tr_straits',1,15,'1','operations'),
('eg-suez-navigation','eg-suez-canal','Suez Canal Authority navigation and news','https://www.suezcanal.gov.eg/English/pages/default.aspx?lang=en','eg_suez',1,60,'1','bulletin'),
('us-cbp-bwt','us-commercial-borders','CBP Border Wait Times — commercial vehicles','https://bwt.cbp.gov/ViewAllPorts','us_bwt',1,15,'1','operations')
ON CONFLICT (id) DO UPDATE SET parser_version=EXCLUDED.parser_version,monitoring_mode=EXCLUDED.monitoring_mode,poll_interval_minutes=EXCLUDED.poll_interval_minutes;
