export const fallbackData = {
  "schema_version": 1,
  "generated_at": "2026-09-10T03:20:00Z",
  "mode": "launch_dataset",
  "coverage": {
    "economies": 7,
    "systems": 7,
    "sources": 7
  },
  "systems": [
    {
      "id": "uk-cds",
      "name": "Customs Declaration Service",
      "short_name": "CDS",
      "country_code": "GB",
      "country_name": "United Kingdom",
      "region": "Europe",
      "authority": "HM Revenue & Customs",
      "system_type": "customs",
      "status": "operational",
      "status_label": "Operational",
      "status_detail": "HMRC reports no planned downtime and no current service issues.",
      "signal_basis": "official_status",
      "confidence": "official",
      "timezone": "Europe/London",
      "official_url": "https://www.gov.uk/guidance/customs-declaration-service-service-availability-and-issues",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-07-09T00:00:00Z",
      "freshness_minutes": 1440
    },
    {
      "id": "sg-tradenet",
      "name": "TradeNet",
      "short_name": "TradeNet",
      "country_code": "SG",
      "country_name": "Singapore",
      "region": "Asia-Pacific",
      "authority": "Singapore Customs",
      "system_type": "customs",
      "status": "clear",
      "status_label": "No active advisory",
      "status_detail": "Singapore Customs publishes a recurring maintenance window every Sunday from 04:00 to 08:00 SGT.",
      "signal_basis": "published_schedule",
      "confidence": "official",
      "timezone": "Asia/Singapore",
      "official_url": "https://www.customs.gov.sg/doing-business/quick-links-for-traders/tradenet/what-you-need-to-know-about-tradenet/",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-08-01T00:00:00Z",
      "freshness_minutes": 10080
    },
    {
      "id": "de-atlas",
      "name": "ATLAS / IAA-Plus",
      "short_name": "ATLAS",
      "country_code": "DE",
      "country_name": "Germany",
      "region": "Europe",
      "authority": "German Customs (Zoll)",
      "system_type": "customs",
      "status": "clear",
      "status_label": "No active advisory",
      "status_detail": "IAA-Plus is available now; an official maintenance window is scheduled for 12 September.",
      "signal_basis": "official_notice",
      "confidence": "official",
      "timezone": "Europe/Berlin",
      "official_url": "https://www.iaap.zoll-portal.de/iaap/intro.do",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-09-02T07:29:00Z",
      "freshness_minutes": 1440
    },
    {
      "id": "au-daff-import",
      "name": "Biosecurity import systems",
      "short_name": "DAFF Import",
      "country_code": "AU",
      "country_name": "Australia",
      "region": "Asia-Pacific",
      "authority": "Department of Agriculture, Fisheries and Forestry",
      "system_type": "biosecurity",
      "status": "clear",
      "status_label": "No active advisory",
      "status_detail": "The latest official notices show BICON restored and the 6–7 September multi-system maintenance window completed.",
      "signal_basis": "official_bulletin",
      "confidence": "official",
      "timezone": "Australia/Sydney",
      "official_url": "https://www.agriculture.gov.au/biosecurity-trade/import/online-services/system-notifications/2026",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-09-03T00:00:00Z",
      "freshness_minutes": 1440
    },
    {
      "id": "ie-ais",
      "name": "Automated Import System",
      "short_name": "AIS",
      "country_code": "IE",
      "country_name": "Ireland",
      "region": "Europe",
      "authority": "Revenue Ireland",
      "system_type": "customs",
      "status": "clear",
      "status_label": "No active advisory",
      "status_detail": "AIS V2 Stage 2 is scheduled to go live on 15 September 2026, with a three-month migration window.",
      "signal_basis": "official_notice",
      "confidence": "official",
      "timezone": "Europe/Dublin",
      "official_url": "https://www.revenue.ie/en/customs/businesses/electronic-systems/ais/annex-b-cci/index.aspx",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-06-16T00:00:00Z",
      "freshness_minutes": 10080
    },
    {
      "id": "nl-rotterdam",
      "name": "Port of Rotterdam operations",
      "short_name": "Rotterdam",
      "country_code": "NL",
      "country_name": "Netherlands",
      "region": "Europe",
      "authority": "Port of Rotterdam Authority",
      "system_type": "port",
      "status": "degraded",
      "status_label": "Operational constraint",
      "status_detail": "Official Port Information Notices show amended pilot service for small vessels and a tugboat capacity arrangement active until further notice.",
      "signal_basis": "official_operations",
      "confidence": "official",
      "timezone": "Europe/Amsterdam",
      "official_url": "https://pin.portofrotterdam.com/node/",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-09-09T03:06:00Z",
      "freshness_minutes": 180
    },
    {
      "id": "be-idms",
      "name": "iDMS Imports / CERTEX",
      "short_name": "iDMS",
      "country_code": "BE",
      "country_name": "Belgium",
      "region": "Europe",
      "authority": "Belgian customs system (status relayed by Customs4trade)",
      "system_type": "customs",
      "status": "degraded",
      "status_label": "Degraded",
      "status_detail": "A CERTEX connection issue remains in monitoring status and the emergency procedure is reported active.",
      "signal_basis": "secondary_status",
      "confidence": "reported",
      "timezone": "Europe/Brussels",
      "official_url": "https://status.customs4trade.com/",
      "last_checked_at": "2026-09-10T03:20:00Z",
      "last_changed_at": "2026-09-04T18:51:00Z",
      "freshness_minutes": 180
    }
  ],
  "events": [
    {
      "id": "be-idms-certex-20260904",
      "system_id": "be-idms",
      "country_code": "BE",
      "country_name": "Belgium",
      "region": "Europe",
      "event_type": "system_incident",
      "status": "active",
      "severity": "moderate",
      "confidence": "reported",
      "title": "iDMS imports — CERTEX connection issue",
      "summary": "A CERTEX connection issue is affecting iDMS imports. The emergency procedure is reported active for urgent shipments.",
      "operational_impact": "Import declarations that depend on the CERTEX connection may require the Belgian customs emergency procedure.",
      "workaround": "For urgent shipments, follow the emergency procedure and reference codes published in the source notice.",
      "starts_at": "2026-09-04T14:00:00Z",
      "ends_at": null,
      "all_day": false,
      "source_name": "Customs4trade status (relaying customs-authority information)",
      "source_url": "https://status.customs4trade.com/",
      "source_tier": 3,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "nl-rotterdam-pilot-20260909",
      "system_id": "nl-rotterdam",
      "country_code": "NL",
      "country_name": "Netherlands",
      "region": "Europe",
      "event_type": "port_constraint",
      "status": "active",
      "severity": "moderate",
      "confidence": "official",
      "title": "Amended pilot service for small vessels",
      "summary": "The Port of Rotterdam has an amended pilot service for small vessels active until further notice.",
      "operational_impact": "Pilotage arrangements for affected small vessels may differ from normal operations.",
      "workaround": "Check the current Port Information Notice before arrival or departure planning.",
      "starts_at": "2026-09-09T03:06:00Z",
      "ends_at": null,
      "all_day": false,
      "source_name": "Port of Rotterdam Authority — Port Information Notices",
      "source_url": "https://pin.portofrotterdam.com/node/",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "nl-rotterdam-tugs-20260908",
      "system_id": "nl-rotterdam",
      "country_code": "NL",
      "country_name": "Netherlands",
      "region": "Europe",
      "event_type": "port_constraint",
      "status": "active",
      "severity": "limited",
      "confidence": "official",
      "title": "Boluda tugboat capacity arrangement",
      "summary": "A capacity arrangement for Boluda tugboats is active at Rotterdam until further notice.",
      "operational_impact": "Tug availability or operating arrangements may be constrained for some vessel movements.",
      "workaround": "Consult the current Port Information Notice and local agent for operational requirements.",
      "starts_at": "2026-09-08T15:52:00Z",
      "ends_at": null,
      "all_day": false,
      "source_name": "Port of Rotterdam Authority — Port Information Notices",
      "source_url": "https://pin.portofrotterdam.com/node/",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "de-atlas-maint-20260912",
      "system_id": "de-atlas",
      "country_code": "DE",
      "country_name": "Germany",
      "region": "Europe",
      "event_type": "scheduled_maintenance",
      "status": "upcoming",
      "severity": "moderate",
      "confidence": "official",
      "title": "ATLAS / IAA-Plus scheduled maintenance",
      "summary": "German Customs says IAA-Plus will be unavailable on 12 September from 13:45 to 23:59 local time.",
      "operational_impact": "Internet export declarations through IAA-Plus will be unavailable during the maintenance window.",
      "workaround": "Submit time-sensitive export declarations before the maintenance window where practical.",
      "starts_at": "2026-09-12T11:45:00Z",
      "ends_at": "2026-09-12T21:59:00Z",
      "all_day": false,
      "source_name": "German Customs (Zoll) — IAA-Plus",
      "source_url": "https://www.iaap.zoll-portal.de/iaap/intro.do",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "sg-tradenet-maint-20260913",
      "system_id": "sg-tradenet",
      "country_code": "SG",
      "country_name": "Singapore",
      "region": "Asia-Pacific",
      "event_type": "scheduled_maintenance",
      "status": "upcoming",
      "severity": "moderate",
      "confidence": "official",
      "title": "TradeNet recurring maintenance",
      "summary": "TradeNet is unavailable every Sunday from 04:00 to 08:00 SGT for maintenance.",
      "operational_impact": "TradeNet permit applications and other transactions cannot be processed through the system during the published window.",
      "workaround": "Plan permit submissions around the Sunday maintenance window.",
      "starts_at": "2026-09-12T20:00:00Z",
      "ends_at": "2026-09-13T00:00:00Z",
      "all_day": false,
      "source_name": "Singapore Customs — TradeNet",
      "source_url": "https://www.customs.gov.sg/doing-business/quick-links-for-traders/tradenet/what-you-need-to-know-about-tradenet/",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z",
      "recurrence": "FREQ=WEEKLY;BYDAY=SU"
    },
    {
      "id": "ie-ais-v2-20260915",
      "system_id": "ie-ais",
      "country_code": "IE",
      "country_name": "Ireland",
      "region": "Europe",
      "event_type": "system_cutover",
      "status": "upcoming",
      "severity": "info",
      "confidence": "official",
      "title": "AIS V2 Stage 2 goes live",
      "summary": "Revenue Ireland will deploy AIS V2 Stage 2 on 15 September 2026, introducing a new data set and message structure.",
      "operational_impact": "Importers, customs agents and software providers need to support the revised AIS V2 data set and messages during the migration period.",
      "workaround": "Confirm software readiness and migration plans; AIS V1 remains available during the three-month migration window.",
      "starts_at": "2026-09-15T00:00:00Z",
      "ends_at": "2026-09-16T00:00:00Z",
      "all_day": true,
      "source_name": "Revenue Ireland — AIS V2",
      "source_url": "https://www.revenue.ie/en/customs/businesses/electronic-systems/ais/annex-b-cci/index.aspx",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "au-multi-maint-20260906",
      "system_id": "au-daff-import",
      "country_code": "AU",
      "country_name": "Australia",
      "region": "Asia-Pacific",
      "event_type": "scheduled_maintenance",
      "status": "resolved",
      "severity": "moderate",
      "confidence": "official",
      "title": "DAFF multiple-system service disruption",
      "summary": "Australia's agriculture department scheduled a multi-system service disruption from 6 to 7 September.",
      "operational_impact": "Multiple biosecurity import systems were affected during the maintenance window.",
      "workaround": null,
      "starts_at": "2026-09-06T00:00:00Z",
      "ends_at": "2026-09-07T23:59:00Z",
      "all_day": true,
      "resolved_at": "2026-09-07T23:59:00Z",
      "source_name": "Australian DAFF — Import system notifications",
      "source_url": "https://www.agriculture.gov.au/biosecurity-trade/import/online-services/system-notifications/2026",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "au-bicon-20260903",
      "system_id": "au-daff-import",
      "country_code": "AU",
      "country_name": "Australia",
      "region": "Asia-Pacific",
      "event_type": "system_incident",
      "status": "resolved",
      "severity": "moderate",
      "confidence": "official",
      "title": "BICON unplanned service disruption",
      "summary": "An unplanned BICON service disruption was reported and a services-restored notice was published the same day.",
      "operational_impact": "Biosecurity import condition lookups were temporarily affected.",
      "workaround": null,
      "starts_at": "2026-09-03T00:00:00Z",
      "ends_at": "2026-09-03T23:59:00Z",
      "all_day": true,
      "resolved_at": "2026-09-03T23:59:00Z",
      "source_name": "Australian DAFF — Import system notifications",
      "source_url": "https://www.agriculture.gov.au/biosecurity-trade/import/online-services/system-notifications/2026",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    },
    {
      "id": "nl-rotterdam-lock-20260907",
      "system_id": "nl-rotterdam",
      "country_code": "NL",
      "country_name": "Netherlands",
      "region": "Europe",
      "event_type": "port_constraint",
      "status": "resolved",
      "severity": "moderate",
      "confidence": "official",
      "title": "Rozenburg Lock disruption",
      "summary": "A Rozenburg Lock navigation disruption was activated and subsequently deactivated on 7 September.",
      "operational_impact": "Navigation through the affected lock was temporarily disrupted.",
      "workaround": null,
      "starts_at": "2026-09-07T10:51:00Z",
      "ends_at": "2026-09-07T12:37:00Z",
      "all_day": false,
      "resolved_at": "2026-09-07T12:37:00Z",
      "source_name": "Port of Rotterdam Authority — Port Information Notices",
      "source_url": "https://pin.portofrotterdam.com/node/",
      "source_tier": 1,
      "last_verified_at": "2026-09-10T03:20:00Z"
    }
  ],
  "sources": [
    {
      "id": "hmrc-cds",
      "system_id": "uk-cds",
      "name": "HMRC CDS availability",
      "url": "https://www.gov.uk/guidance/customs-declaration-service-service-availability-and-issues",
      "adapter": "hmrc_cds",
      "source_tier": 1,
      "poll_interval_minutes": 30
    },
    {
      "id": "sg-customs-tradenet",
      "system_id": "sg-tradenet",
      "name": "Singapore Customs TradeNet guide",
      "url": "https://www.customs.gov.sg/doing-business/quick-links-for-traders/tradenet/what-you-need-to-know-about-tradenet/",
      "adapter": "sg_tradenet",
      "source_tier": 1,
      "poll_interval_minutes": 360
    },
    {
      "id": "de-zoll-iaa",
      "system_id": "de-atlas",
      "name": "German Customs IAA-Plus",
      "url": "https://www.iaap.zoll-portal.de/iaap/intro.do",
      "adapter": "de_atlas",
      "source_tier": 1,
      "poll_interval_minutes": 30
    },
    {
      "id": "au-daff-notices",
      "system_id": "au-daff-import",
      "name": "DAFF import system notifications",
      "url": "https://www.agriculture.gov.au/biosecurity-trade/import/online-services/system-notifications/2026",
      "adapter": "au_daff",
      "source_tier": 1,
      "poll_interval_minutes": 60
    },
    {
      "id": "ie-revenue-ais",
      "system_id": "ie-ais",
      "name": "Revenue AIS V2",
      "url": "https://www.revenue.ie/en/customs/businesses/electronic-systems/ais/annex-b-cci/index.aspx",
      "adapter": "ie_ais",
      "source_tier": 1,
      "poll_interval_minutes": 360
    },
    {
      "id": "nl-rotterdam-pin",
      "system_id": "nl-rotterdam",
      "name": "Port of Rotterdam PIN",
      "url": "https://pin.portofrotterdam.com/node/",
      "adapter": "rotterdam_pin",
      "source_tier": 1,
      "poll_interval_minutes": 30
    },
    {
      "id": "c4t-status",
      "system_id": "be-idms",
      "name": "Customs4trade status",
      "url": "https://status.customs4trade.com/",
      "adapter": "c4t_status",
      "source_tier": 3,
      "poll_interval_minutes": 30
    }
  ]
} as const;
