import { getDatabase } from "@netlify/database";
import { fetchText, htmlToText } from "./http.mts";
import { GATEWAY_SOURCES, type SourceDefinition } from "./sources.mts";

async function markSource(db:any, source:SourceDefinition, ok:boolean, hash?:string, error?:string) {
  if (ok) await db.sql`UPDATE sources SET last_checked_at=NOW(),last_success_at=NOW(),health='healthy',failure_count=0,last_hash=${hash||null},last_error=NULL,parser_version=${source.parserVersion},monitoring_mode=${source.monitoringMode},last_changed_at=CASE WHEN last_hash IS DISTINCT FROM ${hash||null} THEN NOW() ELSE last_changed_at END WHERE id=${source.id}`;
  else await db.sql`UPDATE sources SET last_checked_at=NOW(),failure_count=failure_count+1,health=CASE WHEN failure_count>=2 THEN 'failing' ELSE 'degraded' END,last_error=${error||"Unknown fetch error"},parser_version=${source.parserVersion},monitoring_mode=${source.monitoringMode} WHERE id=${source.id}`;
}
async function updateSystem(db:any,id:string,status:string,label:string,detail:string){ await db.sql`UPDATE systems SET status=${status},status_label=${label},status_detail=${detail},last_checked_at=NOW() WHERE id=${id}`; }
const ES_MONTHS=["enero","febrero","marzo","abril","mayo","junio","julio","agosto","septiembre","octubre","noviembre","diciembre"];
function mexicoMonthLabel(now=new Date()){ const parts=new Intl.DateTimeFormat("en-US",{timeZone:"America/Mexico_City",year:"numeric",month:"numeric"}).formatToParts(now); const year=parts.find(p=>p.type==='year')?.value||String(now.getUTCFullYear()); const month=Number(parts.find(p=>p.type==='month')?.value||now.getUTCMonth()+1); return `${ES_MONTHS[month-1]} ${year}`; }
export function parseMexicoVucem(plain:string,now=new Date()){ if(!/Hojas Informativas/i.test(plain))throw new Error("VUCEM information-sheet index not recognized"); const label=mexicoMonthLabel(now); const monthRe=new RegExp(label.replace('septiembre','septiembre|setiembre'),'i'); const hit=monthRe.exec(plain); if(!hit)return{currentMonth:false,alert:false,label}; const after=plain.slice(hit.index,hit.index+2600); const nextMonth=after.slice(label.length).search(/(?:enero|febrero|marzo|abril|mayo|junio|julio|agosto|septiembre|octubre|noviembre|diciembre)\s+20\d{2}/i); const block=nextMonth>0?after.slice(0,nextMonth+label.length):after; const alert=/(mantenimiento|contingencia|indisponib|suspensi[oó]n|restablecimiento)/i.test(block); return{currentMonth:true,alert,label,block:block.slice(0,900)}; }
export function parseIcs2LatestNews(plain:string,now=new Date()){ if(!/Import Control System 2/i.test(plain))throw new Error("ICS2 page not recognized"); const latest=plain.split(/Latest News/i)[1]?.split(/How to prepare/i)[0]||""; const issue=/(technical issues|service unavailable|system unavailable|unavailability|outage|incident)/i.test(latest); const restored=/(back to normal|restored|resolved)/i.test(latest); return{issue:issue&&!restored,restored,latest:latest.slice(0,1800),checkedAt:now.toISOString()}; }
async function runAdapter(db:any,source:SourceDefinition,html:string){ const plain=htmlToText(html); if(source.adapter==='mx_vucem'){const parsed=parseMexicoVucem(plain);if(parsed.alert)await updateSystem(db,source.system,'unknown','Current VUCEM notice published',`The official VUCEM index contains a maintenance, contingency or restoration notice under ${parsed.label}. TradeStatus is withholding an outage state until the notice timing and scope are extracted.`);else await updateSystem(db,source.system,'clear','No current bulletin flagged',parsed.currentMonth?`The official VUCEM index has ${parsed.label} entries but no maintenance or contingency title was parsed. This is bulletin monitoring, not a heartbeat.`:`No ${parsed.label} maintenance or contingency entry is present in the official VUCEM index. This is bulletin monitoring, not a heartbeat.`);return;} if(source.adapter==='eu_ics2'){const parsed=parseIcs2LatestNews(plain);if(parsed.issue)await updateSystem(db,source.system,'degraded','Current incident bulletin','The European Commission ICS2 latest-news section contains a current technical-issue or unavailability notice. Open the official source for scope and business-continuity guidance.');else await updateSystem(db,source.system,'clear','No current central incident bulletin','ICS2 is fully deployed across transport modes. The Commission page is monitored for central incident notices; it is not a live component heartbeat.');return;} throw new Error(`Unknown gateway adapter: ${source.adapter}`); }
async function due(db:any,force:boolean){ if(force)return GATEWAY_SOURCES; const ids=GATEWAY_SOURCES.map(s=>s.id); const rows=await db.sql`SELECT id,last_checked_at,poll_interval_minutes FROM sources WHERE id = ANY(${ids})`; const byId=new Map(rows.map((r:any)=>[r.id,r]));const now=Date.now(); return GATEWAY_SOURCES.filter(s=>{const r:any=byId.get(s.id);return !r?.last_checked_at||now-new Date(r.last_checked_at).getTime()>=Number(r.poll_interval_minutes||s.pollMinutes)*60000*.9;}); }
export async function refreshGatewaySources(force=false){ const db=getDatabase();const sources=await due(db,force);if(!sources.length)return[{source:'gateway-scheduler',ok:true,skipped:true}]; const results=await Promise.allSettled(sources.map(async source=>{try{const {text,hash}=await fetchText(source.url,12000);await runAdapter(db,source,text);await markSource(db,source,true,hash);return{source:source.id,ok:true};}catch(error){const message=error instanceof Error?error.message:String(error);await markSource(db,source,false,undefined,message);throw new Error(`${source.id}: ${message}`);}})); return results.map((r,i)=>r.status==='fulfilled'?r.value:{source:sources[i].id,ok:false,error:r.reason instanceof Error?r.reason.message:String(r.reason)}); }
