import { getDatabase } from "@netlify/database";
import { fetchText } from "./http.mts";
import { PORTWATCH_SOURCES, type SourceDefinition } from "./sources.mts";

type Row = { date:Date; portid:string; portname:string; nTotal:number; nTanker:number; nCargo:number; capacity:number };
type Analysis = { portid:string; portname:string; latestDate:string; latestTotal:number; avg7:number; reference:number; pct:number; band:"severe"|"material"|"below"|"near"|"elevated" };
const META:Record<string,{countryCode:string;countryName:string;region:string;name:string;derivedOnly:boolean}>={
  "eg-suez-canal":{countryCode:"EG",countryName:"Egypt",region:"Middle East & Africa",name:"Suez Canal",derivedOnly:false},
  "pa-panama-canal":{countryCode:"PA",countryName:"Panama",region:"Americas",name:"Panama Canal",derivedOnly:false},
  "tr-turkish-straits":{countryCode:"TR",countryName:"Türkiye",region:"Europe",name:"Bosporus Strait",derivedOnly:false},
  "int-bab-el-mandeb":{countryCode:"INT",countryName:"Yemen / Djibouti",region:"Middle East & Africa",name:"Bab el-Mandeb Strait",derivedOnly:true},
  "int-malacca":{countryCode:"INT",countryName:"Malaysia / Singapore / Indonesia",region:"Asia-Pacific",name:"Strait of Malacca",derivedOnly:true},
  "int-hormuz":{countryCode:"INT",countryName:"Iran / Oman",region:"Middle East & Africa",name:"Strait of Hormuz",derivedOnly:true},
  "za-cape-good-hope":{countryCode:"ZA",countryName:"South Africa",region:"Middle East & Africa",name:"Cape of Good Hope",derivedOnly:true}
};
async function markSource(db:any,source:SourceDefinition,ok:boolean,hash?:string,error?:string){if(ok)await db.sql`UPDATE sources SET last_checked_at=NOW(),last_success_at=NOW(),health='healthy',failure_count=0,last_hash=${hash||null},last_error=NULL,parser_version=${source.parserVersion},monitoring_mode=${source.monitoringMode},last_changed_at=CASE WHEN last_hash IS DISTINCT FROM ${hash||null} THEN NOW() ELSE last_changed_at END WHERE id=${source.id}`;else await db.sql`UPDATE sources SET last_checked_at=NOW(),failure_count=failure_count+1,health=CASE WHEN failure_count>=2 THEN 'failing' ELSE 'degraded' END,last_error=${error||"Unknown fetch error"},parser_version=${source.parserVersion},monitoring_mode=${source.monitoringMode} WHERE id=${source.id}`;}
async function updateDerivedSystem(db:any,id:string,status:string,label:string,detail:string){await db.sql`UPDATE systems SET status=${status},status_label=${label},status_detail=${detail},last_checked_at=NOW(),last_changed_at=CASE WHEN status IS DISTINCT FROM ${status} THEN NOW() ELSE last_changed_at END WHERE id=${id}`;}
function median(values:number[]){const a=[...values].sort((x,y)=>x-y);if(!a.length)return 0;const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2;}
function mean(values:number[]){return values.length?values.reduce((a,b)=>a+b,0)/values.length:0;}
function parseDate(value:unknown){const d=new Date(typeof value==="number"?value:String(value));if(Number.isNaN(d.getTime()))throw new Error(`Unparseable PortWatch date: ${String(value)}`);return d;}
function dayOfYearUTC(d:Date){const start=Date.UTC(d.getUTCFullYear(),0,1);return Math.floor((Date.UTC(d.getUTCFullYear(),d.getUTCMonth(),d.getUTCDate())-start)/86400000)+1;}
function circularDayDistance(a:number,b:number){const diff=Math.abs(a-b);return Math.min(diff,365-diff);}
export function analyzePortWatch(text:string):Analysis{const payload=JSON.parse(text);if(payload.error)throw new Error(`ArcGIS query error: ${payload.error.message||"unknown"}`);const features=Array.isArray(payload.features)?payload.features:[];const rows:Row[]=features.map((f:any)=>f.attributes||{}).filter((a:any)=>a.date!=null&&a.n_total!=null&&Number.isFinite(Number(a.n_total))).map((a:any)=>({date:parseDate(a.date),portid:String(a.portid||""),portname:String(a.portname||""),nTotal:Number(a.n_total),nTanker:Number(a.n_tanker||0),nCargo:Number(a.n_cargo||0),capacity:Number(a.capacity||0)})).sort((a,b)=>a.date.getTime()-b.date.getTime());if(rows.length<40)throw new Error(`PortWatch returned only ${rows.length} usable observations`);const latest=rows.at(-1)!;const avg7=mean(rows.slice(-7).map(r=>r.nTotal));const targetDay=dayOfYearUTC(new Date(Date.UTC(2025,latest.date.getUTCMonth(),latest.date.getUTCDate())));let referenceRows=rows.filter(r=>r.date.getUTCFullYear()===2025&&circularDayDistance(dayOfYearUTC(r.date),targetDay)<=35);if(referenceRows.length<28)referenceRows=rows.filter(r=>r.date.getUTCFullYear()===2025);const reference=median(referenceRows.map(r=>r.nTotal));if(!reference)throw new Error("PortWatch 2025 seasonal reference is unavailable");const pct=avg7/reference*100;const band:Analysis["band"]=pct<35?"severe":pct<65?"material":pct<80?"below":pct>150?"elevated":"near";return{portid:latest.portid,portname:latest.portname,latestDate:latest.date.toISOString().slice(0,10),latestTotal:latest.nTotal,avg7:Number(avg7.toFixed(1)),reference:Number(reference.toFixed(1)),pct:Number(pct.toFixed(1)),band};}
async function storeMetric(db:any,source:SourceDefinition,a:Analysis){await db.sql`INSERT INTO chokepoint_metrics (system_id,source_id,observed_date,latest_total,avg_7d,seasonal_reference,pct_reference,band,recorded_at) VALUES (${source.system},${source.id},${a.latestDate},${a.latestTotal},${a.avg7},${a.reference},${a.pct},${a.band},NOW()) ON CONFLICT (system_id,source_id,observed_date) DO UPDATE SET latest_total=EXCLUDED.latest_total,avg_7d=EXCLUDED.avg_7d,seasonal_reference=EXCLUDED.seasonal_reference,pct_reference=EXCLUDED.pct_reference,band=EXCLUDED.band,recorded_at=NOW()`;}
async function upsertSignalEvent(db:any,source:SourceDefinition,a:Analysis,kind:"drop"|"surge"){const meta=META[source.system];if(!meta)throw new Error(`Missing PortWatch metadata for ${source.system}`);const id=`${source.system}-portwatch-${kind}`;const isDrop=kind==="drop";const severity=isDrop?(a.pct<35?"major":"moderate"):"info";const title=isDrop?`${meta.name} traffic materially below reference`:`${meta.name} traffic elevated versus reference`;const summary=`IMF PortWatch's latest settled data (${a.latestDate}) show a 7-day average of ${a.avg7} vessel transits/day, ${a.pct}% of the 2025 seasonal reference (${a.reference}/day).`;const impact=isDrop?"Sustained lower transit counts can indicate rerouting, restrictions, conflict effects, demand changes or other disruption. AIS counts alone do not prove that a passage is closed.":"Elevated transits can indicate rerouting from another corridor, seasonal effects or stronger underlying traffic. This is a traffic signal, not an operational restriction.";const workaround="Check the relevant passage authority, carrier advisories and local security notices before making routing decisions.";await db.sql`INSERT INTO events (id,system_id,country_code,country_name,region,event_type,status,severity,confidence,title,summary,operational_impact,workaround,starts_at,ends_at,all_day,source_name,source_url,source_tier,last_verified_at,fingerprint) VALUES (${id},${source.system},${meta.countryCode},${meta.countryName},${meta.region},${isDrop?"traffic_anomaly":"traffic_surge"},'active',${severity},'derived',${title},${summary},${impact},${workaround},${a.latestDate+"T00:00:00Z"},NULL,TRUE,'International Monetary Fund — PortWatch',${source.url},1,NOW(),${id}) ON CONFLICT (id) DO UPDATE SET severity=EXCLUDED.severity,title=EXCLUDED.title,summary=EXCLUDED.summary,operational_impact=EXCLUDED.operational_impact,workaround=EXCLUDED.workaround,starts_at=EXCLUDED.starts_at,last_verified_at=NOW(),updated_at=NOW(),resolved_at=NULL`;}
async function resolveSignalEvent(db:any,systemId:string,kind:"drop"|"surge"){const id=`${systemId}-portwatch-${kind}`;await db.sql`UPDATE events SET resolved_at=COALESCE(resolved_at,NOW()),status='resolved',updated_at=NOW(),last_verified_at=NOW() WHERE id=${id} AND resolved_at IS NULL`;}
async function refreshOne(db:any,source:SourceDefinition,text:string){const a=analyzePortWatch(text);const meta=META[source.system];if(!meta)throw new Error(`Missing PortWatch metadata for ${source.system}`);await storeMetric(db,source,a);const lag=Math.max(0,Math.floor((Date.now()-new Date(a.latestDate+"T00:00:00Z").getTime())/86400000));const suffix=`Latest settled day ${a.latestDate}; 7-day average ${a.avg7}/day versus 2025 seasonal reference ${a.reference}/day (${a.pct}%). PortWatch is AIS-derived and published with a lag${lag?` of about ${lag} day${lag===1?"":"s"}`:""}.`;if(a.pct<65)await upsertSignalEvent(db,source,a,"drop");else await resolveSignalEvent(db,source.system,"drop");if(a.pct>150)await upsertSignalEvent(db,source,a,"surge");else await resolveSignalEvent(db,source.system,"surge");if(!meta.derivedOnly)return;if(a.band==="severe")await updateDerivedSystem(db,source.system,"degraded","Traffic severely reduced",suffix);else if(a.band==="material")await updateDerivedSystem(db,source.system,"degraded","Traffic materially below reference",suffix);else if(a.band==="below")await updateDerivedSystem(db,source.system,"degraded","Traffic below reference",suffix);else if(a.band==="elevated")await updateDerivedSystem(db,source.system,"clear","Elevated traffic / rerouting signal",suffix);else await updateDerivedSystem(db,source.system,"clear","Traffic near seasonal reference",suffix);}
async function due(db:any,force:boolean){if(force)return PORTWATCH_SOURCES;const ids=PORTWATCH_SOURCES.map(s=>s.id);const rows=await db.sql`SELECT id,last_checked_at,poll_interval_minutes FROM sources WHERE id = ANY(${ids})`;const byId=new Map(rows.map((r:any)=>[r.id,r]));const now=Date.now();return PORTWATCH_SOURCES.filter(s=>{const r:any=byId.get(s.id);return !r?.last_checked_at||now-new Date(r.last_checked_at).getTime()>=Number(r.poll_interval_minutes||s.pollMinutes)*60000*.9;});}
export async function refreshPortWatchSources(force=false){const db=getDatabase();const sources=await due(db,force);if(!sources.length)return[{source:"portwatch-scheduler",ok:true,skipped:true}];const results=await Promise.allSettled(sources.map(async source=>{try{const {text,hash}=await fetchText(source.url,15000);await refreshOne(db,source,text);await markSource(db,source,true,hash);return{source:source.id,ok:true};}catch(error){const message=error instanceof Error?error.message:String(error);await markSource(db,source,false,undefined,message);throw new Error(`${source.id}: ${message}`);}}));return results.map((r,i)=>r.status==="fulfilled"?r.value:{source:sources[i].id,ok:false,error:r.reason instanceof Error?r.reason.message:String(r.reason)});}
